CC=gcc
DEBUG_FLAGS=-g -pg
CFLAGS=$(DEBUG_FLAGS) -O3 -Wall -Wpedantic -lz -std=gnu11 -fopenmp
PROG=fastDBarcode

all:
	mkdir -p ./bin
	$(CC) $(CFLAGS) -o ./bin/$(PROG) ./src/main.c ./src/fdb.c

clean:
	rm -rvf ./bin
